### PR TITLE
fix error in slime-parse.el and  slime-fontifying-fu.el when use the GCC Emacs

### PR DESCRIPTION
**Pull request by madosuki**

### CODE REVIEW

**Comment by stassats** [comment]
What is GCC Emacs and why is it different?

**Comment by joaotavora** [comment]
https://github.com/slime/slime/commit/f135f69c5c97bb1f2456d05ee1e84ad6b4495ca3

**Comment by stassats** [comment]
Reverting that may make sense. But the other changes seem weird.

**Comment by madosuki** [comment]
That is certainly true. I made mistakes, and so I close that commit.

**Pull request closed without merging**
