### PR TITLE
new binding: slime-cycle-connections-back on C-c C-x p

### PR DESCRIPTION
**Pull request by adlai**

### CODE REVIEW

**Comment by luismbo** [comment]
Can you add a ChangeLog entry and add the command to slime-selector too? (Feel free to rebase.)

**Comment by adlai** [comment]
@luismbo before merging, maybe I should change this version to better parallel the implementation in capitaomorte/sly@24f8636 ?

**Comment by luismbo** [comment]
@adlai your call.

**Comment by capitaomorte** [comment]
@adlai if you do that, note that I left the `dont-wrap` parameter unimplemented, out of lazyness

**Comment by capitaomorte** [comment]
@adlai Never mind, I did implement it :-) sorry for the noise

**Comment by adlai** [comment]
Changed function names to give a similar interface to the sly version. I'd like to have at least this minimal version in mainline slime, found myself missing it in a new installation...

**Comment by adlai** [comment]
rebased onto current HEAD

**Comment by luismbo** [comment]
@adlai pushed along with some small bugfixes. Thanks!

BTW, I find the following hack useful...

```el
(defun slime-switch-connection (connection)
  (interactive
   (list (cl-find (ido-completing-read "Select connection: "
                                       (mapcar #'slime-connection-name
                                               (let ((next (member (slime-current-connection)
                                                                   slime-net-processes)))
                                                 (append next
                                                         (reverse (cl-set-difference slime-net-processes
                                                                                     next)))))
                                       nil nil nil nil
                                       (slime-connection-name (slime-current-connection)))
                  slime-net-processes
                  :key #'slime-connection-name)))
  (slime-select-connection connection)
  (run-hooks 'slime-cycle-connections-hook)
  (message "Lisp: %s %s"
           (slime-connection-name connection)
           (process-contact connection)))
```

Does it suit your use cases? It's probably worth cleaning up.

**Comment by luismbo** [comment]
Oh, note to self: slime.texi needs to updated before this issue is closed.

**Pull request closed without merging**
