### PR TITLE
Remove ChangeLog files

### PR DESCRIPTION
**Pull request by luismbo**
This pull request removes SLIME's ChangeLog files. The rationale for this is twofold:

1. ChangeLog files introduce merge conflicts all too often. While Gnulib's ChangeLog merge driver attempts to solve that problem, installing and setting it up is troublesome and doesn't work on GitHub anyway.

2. While it is certaintly possible to write great ChangeLog entries, Emacs's ChangeLog being a notable example, the ChangeLog format promotes describing *what* changed rather than *why*.

### CODE REVIEW

**Comment by sionescu** [comment]
Good idea.

**Comment by PuercoPop** [comment]
Maybe include a section on commit messages in Contributing.md. Without a changelog commit messages are more important.

**Comment by attila-lendvai** [comment]
let's say bye to that one last unnecessary merge conflict that, ironically enough, shows up above at the patch that removes the ChangeLog file... :)

**Comment by stassats** [comment]
Nobody reads them anyhow. Good riddance.

**Comment by luismbo** [comment]
@PuercoPop makes sense! I'll include a link to http://chris.beams.io/posts/git-commit/. Would you recommend a different article perhaps? Feel free to suggest specific verbiage too.

**Comment by luismbo** [comment]
@attila-lendvai heh, it's an actual bug rather than a merge conflict, but, yeah, I think one last ChangeLog merge conflict will show up in this merge request, eventually. :-)

**Comment by luismbo** [comment]
Finally pushed this to master!

**Pull request closed without merging**
