### PR TITLE
fix swank-kawa #294

### PR DESCRIPTION
**Pull request by s-kostyaev**

### CODE REVIEW

**Comment by luismbo** [comment]
Nice job. Do you have any idea why this changed? Perhaps it has to do with JVM or Kawa versions?

**Comment by s-kostyaev** [comment]
I think it may be kawa version, because I was try slime & kawa with various jvm versions and have issue on both. I need to read kawa changelog for fully understanding.

**Comment by luismbo** [comment]
Should you not reach a definitive conclusion, perhaps the following conservative approach would work well?

```scheme
(let* ((class :: <class-type> (1st (append (! classesByName vm "swank-kawa")
                                           (! classesByName vm "swank$Mnkawa"))))
       ...)
  ...)
```

**Comment by s-kostyaev** [comment]
Backward compatibility is very good idea.

**Comment by s-kostyaev** [comment]
But I can't do this:
error Argument #1 '[]' to 'append' has wrong type (java.util.Collections$UnmodifiableRandomAccessList)

**Comment by luismbo** [comment]
Uh, oh, seems like your Java fears came true. Can you figure out how to append two collections?

**Comment by s-kostyaev** [comment]
I can fix it without Java black magic :)

**Comment by luismbo** [comment]
Hmm, try `vector-append` instead of `append`.

**Comment by s-kostyaev** [comment]
With `vector-append` I have the same exception. Do you think that my current solution is bad?

**Comment by luismbo** [comment]
No, it's fine. Appending would be slightly more elegant, that's all.

**Comment by s-kostyaev** [comment]
For now I don't know how to append `Unmodifiable` with kawa :)

**Comment by luismbo** [comment]
No problem. Applied your fix in 0525b90, thanks!

**Pull request closed without merging**
