### PR TITLE
readtable-aware swank/slime

### PR DESCRIPTION
**Pull request by budden**
Reissue of https://github.com/slime/slime/pull/259

See also 
https://github.com/melisgl/named-readtables/pull/8
http://thread.gmane.org/gmane.lisp.slime.devel/11574
Current pull request have no essential differencies with #259

### CODE REVIEW

**Comment by budden** [comment]
Hi! My previous solution was not perfect, if we take the compatibility into account. I suggest to discuss an improved version: 

https://bitbucket.org/budden/clcon/src/e3c40c555295336a3a13c506cce6a179f9dd8713/doc/how-to-support-readtable-with-slime.md?fileviewer=file-view-default

**Comment by luismbo** [comment]
Closing because this pull request for your master branch is a bit confusing since it's picking lots of unrelated things.

**Comment by budden** [comment]
Hi Luís!

That's ok. FYI, I've changed my mind, and I'm not planning to submit
any patch for main SLIME repo - it is much better for me to continue
maintaining my patched https://github.com/budden/slime in sync with
never versions of SLIME.

2018-01-02 14:19 GMT+03:00, Luís Oliveira <notifications@github.com>:

**Comment by joaotavora** [comment]
@budden, if you didn't know, SLY has [readtable-aware support](https://github.com/joaotavora/sly-named-readtables) available as a separate contrib. I think the original idea came from a post of yours a few years ago.

@luismbo sorry for the plug here and a happy new year :-)

**Comment by budden** [comment]
Hi!

Thanks, I remember about SLY and even took a look at its site today
(but I was looking for single-threaded operation mode). Actually for
now I'm switching out of CL because I'm out of my resources and have
to find a work for money. I can't find a work in CL, so I started to
learn JS.

If I ever turn my way to CL again, SLY will be one of the first things
to look at :)

Happy New Year for you too and all the best! Good to know that your
project is still alive :)

**Comment by budden** [comment]
Sorry, wrong list...

2018-01-02 17:53 GMT+03:00, 73budden . <budden73@gmail.com>:
> Hi!
>
> Thanks, I remember about SLY and even took a look at its site today
> (but I was looking for single-threaded operation mode). Actually for
> now I'm switching out of CL because I'm out of my resources and have
> to find a work for money. I can't find a work in CL, so I started to
> learn JS.
>
> If I ever turn my way to CL again, SLY will be one of the first things
> to look at :)
>
> Happy New Year for you too and all the best! Good to know that your
> project is still alive :)
>

**Pull request closed without merging**
