### PR TITLE
Fixed a problem with intering symbols into the user's package.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
This should fix the problem described in issue https://github.com/slime/slime/issues/780

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
@stassats is there any chance this PR to be merged in near future?

I'm using the latest Slime version from Ultralisp and many of my processes are broken now because of this issue :(

**Comment by stassats** [comment]
How did it work before?

**Comment by svetlyak40wt** [comment]
Well, probably something did changed recently in my environment and it become sensitive to current package symbol pollition :(

Anyway I think it is a good taste – to not intern symbols during in a defpackage form.

**Comment by stassats** [comment]
Ok, I thought ASDF used dummy packages or something, apparently not.

**Pull request merged**
