### PR TITLE
Be more robust when source positions in clasp are still a cons

### PR DESCRIPTION
**Pull request by kpoeck**
see discussion in
https://irclog.tymoon.eu/freenode/%23clasp?around=1610214862#1610214862

### CODE REVIEW

**Comment by stassats** [comment]
When you say "more robust", does it mean there's something erroneous? And I would prefer a LET instead, especially when you need a PROGN.

**Comment by kpoeck** [comment]
it is to avoid this error in slime with clasp for C-c C-k
```lisp
Add support for source-file-info for (#<SOURCE-POS-INFO :fileId 675 :filepos 10937 :lineno 226 :column 0> . #<SOURCE-POS-INFO :fileId 675 :filepos 15176 :lineno 306 :column 22>)
   [Condition of type CORE:SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [ABORT] Abort compilation.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Abort the process (#<PROCESS "worker" @0x143439eb1 (Running)>)

Backtrace:
  0: l_SIGNAL-SIMPLE-ERROR^CORE^FN^^
  1: (CORE:SIGNAL-SIMPLE-ERROR CORE:SIMPLE-PROGRAM-ERROR NIL "~a" ("Add support for source-file-info for (#<SOURCE-POS-INFO :fileId 675 :filepos 10937 :lineno 226 :column 0> . #<SOURCE-POS-INFO :fileId 675..
  2: (CORE:FILE-SCOPE (#<SOURCE-POS-INFO :fileId 675 :filepos 10937 :lineno 226 :column 0> . #<SOURCE-POS-INFO :fileId 675 :filepos 15176 :lineno 306 :column 22>))
  3: l_CONDITION-LOCATION^SWANK/CLASP^FN^^
  4: (SWANK/CLASP::CONDITION-LOCATION (#<SOURCE-POS-INFO :fileId 675 :filepos 10937 :lineno 226 :column 0> . #<SOURCE-POS-INFO :fileId 675 :filepos 15176 :lineno 306 :column 22>))
  5: l_SIGNAL-COMPILER-CONDITION^SWANK/CLASP^FN^^
  6: (SWANK/CLASP::SIGNAL-COMPILER-CONDITION #<SIMPLE-WARNING> (#<SOURCE-POS-INFO :fileId 675 :filepos 10937 :lineno 226 :column 0> . #<SOURCE-POS-INFO :fileId 675 :filepos 15176 :lineno 306 :column 22>))
  7: (SWANK/CLASP::HANDLE-COMPILER-CONDITION #<SIMPLE-WARNING>)
  8: l_%SIGNAL^CORE^FN^^
  9: (CORE::%SIGNAL #<SIMPLE-WARNING>)
 10: (SIGNAL #<SIMPLE-WARNING>)
 11: l_COMPILER-WARNING-HANDLER^COMPILER^FN^^
 12: (COMPILER::COMPILER-WARNING-HANDLER #<SIMPLE-WARNING>)
 13: l_%SIGNAL^CORE^FN^^
 14: (CORE::%SIGNAL #<SIMPLE-WARNING>)
 15: (SIGNAL #<SIMPLE-WARNING>)
 16: l_WARN^COMMON-LISP^FN^^
 17: (WARN #<SIMPLE-WARNING>)
 18: (MAPC #<FUNCTION WARN> (#<CLEAVIR-BIR:UNUSED-VARIABLE> #<SIMPLE-WARNING> #<SIMPLE-WARNING> #<SIMPLE-WARNING> #<SIMPLE-WARNING> #<SIMPLE-WARNING> ...))
 19: l_CCLASP-LOOP2^COMPILER^FN^^
 20: (COMPILER::CCLASP-LOOP2 #<IOSTREAM-STREAM #P"/Users/meister/Development/cando/extensions/cando/src/lisp/leap/pdb.lisp"> NIL :OPTIMIZE T :OPTIMIZE-LEVEL 3 :OUTPUT-PATH #P"/private/tmp/clasp-swank-compi..
 21: l_COMPILE-FILE-TO-RESULT^COMPILER^FN^^
 22: (COMPILER::COMPILE-FILE-TO-RESULT #P"/Users/meister/Development/cando/extensions/cando/src/lisp/leap/pdb.lisp" :OUTPUT-TYPE :FASP :OUTPUT-PATH #P"/private/tmp/clasp-swank-compile-file-UyOBiq.fasp" :EN..
...
````

**Comment by kpoeck** [comment]
I did drop the let, tested with clasp and updated the pr, please check

**Comment by kpoeck** [comment]
And now drmeister fixed it in a similar way

**Pull request closed without merging**
