### PR TITLE
Drop incomplete compatibility support for Emacs <24.3

### PR DESCRIPTION
**Pull request by phikal**
Taken from https://github.com/slime/slime/pull/809#issuecomment-1937109140.

### CODE REVIEW

**Comment by phikal** [comment]
Thanks.  Just out of curiosity, are there plans for a (point) release soon?

**Comment by pedro-w** [comment]
Also out of curiosity, what's the oldest version of emacs that slime supports?

**Comment by stassats** [comment]
Not yet. Once the new changes are tested enough.

**Comment by phikal** [comment]
> Also out of curiosity, what's the oldest version of emacs that slime supports?

As of [this](https://github.com/slime/slime/pull/812/files#diff-d3ed4f2cba6410f337abb7a0e062264517f3b6f85910b6ffdfc5a54139179e7dR4) changeset, Emacs 24.3.

**Pull request merged**
