### PR TITLE
Replace slime-autoloads.el with magic comments i.e. autoload cookies

### PR DESCRIPTION
**Pull request by ylluminarious**
As per https://github.com/slime/slime/issues/443

### CODE REVIEW

**Comment by stassats** [comment]
Does that break (require 'slime-autoloads)?

**Comment by ylluminarious** [comment]
@stassats Yes, I think it does. Fixed with a new commit.

**Comment by stassats** [comment]
But somebody doing (require 'slime-autoloads) will still fail.

**Comment by ylluminarious** [comment]
@stassats You're never supposed to require an autoload file. That's antithetical to their purpose.

**Comment by stassats** [comment]
Well, I'm never supposed to break old setups.

**Comment by stassats** [comment]
And how else are autoloads going to work if they are not loaded?

**Comment by ylluminarious** [comment]
@stassats You're not going to break any old setups. Anyone who has been using autoloads since their creation has never used code like `(require 'slime-autoloads)`. Please see [the manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html) for more details.

**Comment by joaotavora** [comment]
> You're never supposed to require an autoload file, That's antithetical to their purpose.

@ylluminarious, sorry that's wrong. You're indeed supposed to `require` or `load` these small files from your setup, or have the package manager do it for you. The package manager may, prior to that, generate the autoload files (or a big autoloads file for many packages), from the cookies it finds. 

When I wrote that comment, `(require 'slime-autoloads)` was very much in my mind. I think you're confusing two things: it can be automatically generated *and* still be in the dist.

**Comment by ylluminarious** [comment]
@joaotavora Ok, yes, you're right. I'm talking about specifically about end-users and their initialization setups. What I meant above is that 99.99% of end-users have never and will never `require` an autoloads file unless they're doing something quite strange. Aside from end-users, yes, the package manager will have to `require` the autoloads file, but the autoloads file is supposed to be auto-generated by the package manager, as you mentioned. And if the end-user is using a local copy of SLIME without ELPA, they can just use `update-file-autoloads` and friends to the same effect.

Either way, I see no problem here. The autoloads file will be generated somehow or another so whoever needs to `require` it will have no problem. Are there any actual problems with this patch aside from that?

**Comment by stassats** [comment]
>they can just

is not good, nothing should change.

**Comment by ylluminarious** [comment]
@stassats Did you read the documentation I sent you? That is how autoloads are *supposed* to function. The `<package>-autoloads.el` file is *supposed* to be auto-generated. A user who is using a local copy of any package is already aware of this or they're not using autoloads. You simply are not going to break anything for any end-user.

**Comment by stassats** [comment]
Well, I don't need this change and I don't use autoloads. If you want it to be accepted you have to ensure it preserves compatibility and that means leaving slime-autoloads.el in place.

**Comment by stassats** [comment]
There's no discussion — slime-autoloads.el stays, whether it's written manually or generated from the cookies, but it stays.

**Comment by ylluminarious** [comment]
@stassats Great! Then that means that we're good here. It *will* be generated from cookies by a package manager or by a user.

**Comment by stassats** [comment]
I don't use a package manager. Does quicklisp generate it too?

**Comment by ylluminarious** [comment]
@stassats Quicklisp does not have Emacs-specific code, since most of the packages distributed by Quicklisp are in Common Lisp and have nothing to do with Emacs. Therefore, Quicklisp does not automatically generate Emacs autoloads. It would only be applicable to a very small subset of packages in Quicklisp.

So, if someone got SLIME from Quicklisp, this is an instance wherein they would either:

1. Add SLIME to their path manually, or
2. Generate an autoloads file manually

This is the exact same set of options a user would take if they use SLIME from a local `git` clone or a tarball. It's what I was trying to tell you above. I know this because I deal with many such packages and I know a number of other Emacs users do things in the same way. Since you do not use a package manager, you might want to search around and see how people actually do things in a package manager so that you can understand that this whole discussion is actually a non-issue.

**Comment by stassats** [comment]
I don't have any more time to spend on this. I can't accept breaking changes that even contradict our manual https://common-lisp.net/project/slime/doc/html/Installation.html

**Comment by ylluminarious** [comment]
Hmm, seems that it's not showing up since you closed the PR. I'll make a new one so that there are no contradictions in the manual.

**Pull request closed without merging**
