### PR TITLE
Added customizable lighter for Autodoc Mode

### PR DESCRIPTION
**Pull request by sirikid**

### CODE REVIEW

**Comment by luismbo** [comment]
(note: this implements feature request #409)

**Comment by luismbo** [comment]
Should we add something to this section of the manual? https://common-lisp.net/project/slime/doc/html/slime_002dautodoc_002dmode.html

**Comment by luismbo** [comment]
Also, minor nitpick: git commit titles should be written in the imperative. (Rule number 5 in https://chris.beams.io/posts/git-commit/ :-))

**Comment by sirikid** [comment]
Can I somehow speed up the merge or improve the pull-request?

**Comment by luismbo** [comment]
Yes! You can address my comments.

**Comment by sirikid** [comment]
I get it. I can't change the commit message, but I'll try to improve the documentation.

**Comment by sirikid** [comment]
I added a paragraph about the new variable to the documentation.

**Comment by luismbo** [comment]
Thanks @sirikid!

**Pull request merged**
