### PR TITLE
:mips and :mipsel

### PR DESCRIPTION
**Pull request by tapioco71**
Added :mips and :mipsel keyword in swank-loader.lisp \*architecture-features\*.

### CODE REVIEW

**Comment by luismbo** [comment]
Hmm. You've already sent this change back in June https://github.com/slime/slime/commit/06c58fa0ae2ed0460c1f5ecfa42e4fe97408687a and it was accepted.

**Comment by tapioco71** [comment]
Yes, but latest upgrade didn't fixed it...

**Comment by luismbo** [comment]
Not sure what you mean. Are you having trouble updating your git repository?

**Comment by tapioco71** [comment]
No, I updated my quicklisp system and it downloaded slime-2.14, but no
fixed on it. Which version should be downloaded to have this fixed? Thanks.

**Comment by luismbo** [comment]
Hasn't been released yet. The fix will be in the next release. Probably in September.

**Comment by tapioco71** [comment]
Sorry for all that, it's my fault, I cloned the git repository and patches
are there, alive and kicking! Thanks again!

**Pull request closed without merging**
