### PR TITLE
Make fuzzy completion up/down navigation wrap around the edges

### PR DESCRIPTION
**Pull request by wsgac**
When using fuzzy completion I am frequently facing a fairly long completion list. I thought that not being able to wrap around the edges (i.e. scroll up from the beginning and arrive at the end and vice versa) was a bit counter-intuitive. So I modified the `slime-fuzzy-next` and `slime-fuzzy-prev` functions.

### CODE REVIEW

**Comment by attila-lendvai** [comment]
if you switch focus to the completion buffer, then you can jump to the beginning/end with the usual shortcuts. unfortunately the highlight is not updated, which should/could be fixed.

generally i'm not happy about such wrapping around, because it's often confusing for me, but this is just one opinion. i also rarely even look at anything one page down in the fuzzy list. if what i'm looking for is not at the top, then i usually type more and update the fuzzy list.

**Comment by wsgac** [comment]
Well, yes, you can jump to the completion buffer, but to me the whole point of it intercepting navigation keys from another buffer is to make completion less of a cognitive distraction. I tested this change among some people at work and they liked it. Perhaps this behavior could be switched on/off with a configuration variable.

**Comment by attila-lendvai** [comment]
don't add a config, that's pointless extra complexity.

if people generally like this change then just commit it as-is.

**Comment by wsgac** [comment]
Yup, at least that's the impression I get by talking to other Lispers.

**Comment by wsgac** [comment]
I believe there's nothing more to do here. Can you please merge this change?

**Pull request closed without merging**
