### PR TITLE
Fixed autoload spec of ‘hyperspec-lookup’

### PR DESCRIPTION
**Pull request by mrkkrp**
Previously name of file to load was incorrect.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Any update on this PR? I would like to use `hyperspec-lookup`.

**Comment by luismbo** [comment]
Can you add a ChangeLog entry?

**Comment by mrkkrp** [comment]
@luismbo, here it is.

**Comment by mrkkrp** [comment]
Diff is weird, I pulled all you've done while my PR hanged here, and then force pushed to be even with your `master`. Now my local `master` is OK, but the diff here is from the first try (that caused merge conflicts, of course). I better open new pull request.

**Pull request closed without merging**
