### PR TITLE
colour change

### PR DESCRIPTION
**Pull request by bigos**
It's easier to read on dark backgrounds.

http://emacs.stackexchange.com/questions/21275/looking-for-a-better-theme-fix-in-slime

### CODE REVIEW

**Comment by luismbo** [comment]
Hmm. How about some sort of light red?

**Comment by bigos** [comment]
light salmon could be OK

(((class color) (background dark)) (:foreground "light salmon"))

I have created a simple HTML file for experimenting with colours, so someone could try more colours.

https://gist.github.com/bigos/8bf4ff40c1e6299758d44946c2357334

**Comment by luismbo** [comment]
Is there an easy way to preview that html file without cloning the gist locally?

**Comment by luismbo** [comment]
Found a way: http://htmlpreview.github.io/?gist.githubusercontent.com/bigos/8bf4ff40c1e6299758d44946c2357334/raw/64679c09701612e70f0af3802912bc6339fd660f/colours.html

**Comment by ioannad** [comment]
@luismbo I also find light-salmon easier on the eyes than yellow, on both dark backgrounds. 
Could this be merged if @bigos changes "Yellow" to "light salmon"?

**Comment by bigos** [comment]
I think emacs has introduced the ability to have different settings depending on the screen being dark or light. Please feel free to change the way you want.

Also, let me know what you think of the function bg-light that can be found here and could be used to automate the selection for you.

https://github.com/bigos/prelude/blob/master/personal/organised.org#parentheses-coloring

**Comment by luismbo** [comment]
@ioannad sounds fine. It'd be nice to inherit from some other semantically similar face, but `list-faces-display` doesn't turn up anything obvious at first glance.

**Comment by ioannad** [comment]
@luismbo I also couldn't find another slime-related face from which `slime-repl-inputed-output-face` could inherit from. 

@bigos I like the use of the hook and `defadvice` in your org file, and I find `bg-light` a nice way to finely customise the colours. However, I still think the default for `(background dark)` here should be "light salmon", as this is the simplest solution to the issue described in the stackexchange link you posted.

I could make the change in your pull request, as you suggested, if you give me the necessary permissions to do so (see https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by easye** [comment]
> On Jun 27, 2019, at 23:42, Ioanna M Dimitriou H <notifications@github.com> wrote:
> 
> @luismbo I also couldn't find another slime-related face from which slime-repl-inputed-output-face could inherit from.
> 
> @bigos I like the use of the hook and defadvice in your org file, and I find bg-light a nice way to finely customise the colours. However, I still think the default for (background dark) here should be "light salmon", as this is the simplest solution to the issue described in the stackexchange link you posted.
> 
> I could make the change in your pull request, as you suggested, if you give me the necessary permissions to do so (see https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

I would nominate Ioanna as a reliable steward of SLIME, if that counts towards @luismbo’s inclination. 




--
"No, this is not a disentanglement, but a progressive /knotting-into/."

**Comment by stassats** [comment]
> I would nominate Ioanna as a reliable steward of SLIME, if that counts towards @luismbo’s inclination.
It's hard to asses reliability without any prior commits or contributions.

**Comment by bigos** [comment]
https://github.com/slime/slime/pull/313/files#diff-72c8188252665307fd3ba137aaed0f1e done

**Comment by luismbo** [comment]
Thanks @bigos, @ioannad!

**Pull request merged**
