### PR TITLE
[WIP] Add working CI via GitHub Actions

### PR DESCRIPTION
**Pull request by purcell**
Hi - I noticed your CI is failing (see #541) and I thought I'd try submitting an equivalent GitHub Actions config to see if I can help fix it. Will update here when and if I get it working. :-)

### CODE REVIEW

**Comment by purcell** [comment]
That's mostly working:

* CCL and SBCL
* Linux and MacOS
* Same selection of Emacs versions as before, plus the latest HEAD

The Linux builders run in < 2mins, the MacOS ones fail, and I suspect there may be a timeout which needs extending? We could remove that platform if desired, but it's kinda nice to have cross-platform checks.

(I've added a build status badge to the README, and if you eventually merge this, you might also consider removing the travis badge and config to discontinue its use.)

**Comment by stassats** [comment]
I disabled the macos target, but the some tests are still flaky.

**Comment by luismbo** [comment]
The Travis build is actually passing, the badge is just not being updated for some reason. In any case, GitHub Actions sounds good. I'll remove the Travis setup. Thanks @purcell.

**Comment by luismbo** [comment]
@stassats the nix packages for SBCL seem a bit out-of-date, do we care?

**Comment by stassats** [comment]
It's not that old, the one shipped with ubuntu is much older, so, short of building it manually, this should be ok.

**Comment by luismbo** [comment]
OK. If we ever run into trouble with the nix packages we can always revert back to the roswell way: `curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh` and `LISP=ros run -L $LISP`. Removed Travis CI in 5f48c8c1f3c1538cccc155268d304172e6339aa7.

**Comment by purcell** [comment]
Thanks for the merge, folks!

> OK. If we ever run into trouble with the nix packages we can always revert back to the roswell way

Yeah, I figured try the nix way, since that's what the `setup-emacs` action uses under the hood. It should track the Nix unstable channel by default, so package versions should stay pretty up-to-date overall.

**Comment by luismbo** [comment]
@purcell the nix step has stopped working. Any idea why?

**Comment by purcell** [comment]
Fixed in #593

**Comment by luismbo** [comment]
Thanks @purcell!

**Comment by purcell** [comment]
No worries, thanks for tagging me in.

**Pull request merged**
